/**
 * Types for the Data Guide explorer. Mirrors the shape of
 * `app/data-guide/guide.json`, which is generated by the kit in
 * `connect-tool/data-guide/` (see that folder's README).
 */

/** Capability columns, in display order. */
export const PLATFORMS = [
  'YouTube',
  'Instagram',
  'TikTok',
  'Threads',
  'Facebook',
  'LinkedIn',
  'Twitch',
] as const;

export type Platform = (typeof PLATFORMS)[number];

/** A boolean keyed by platform (support / offered maps). */
export type PlatformFlags = Record<Platform, boolean>;

/** A string keyed by platform — only the offered-with-caveat entries exist. */
export type PlatformCaveats = Partial<Record<Platform, string>>;

export interface GuideField {
  name: string;
  desc: string;
  type: string;
  family: string;
  /** 'production' | 'planned' | 'beta' | … — non-production shows a pill. */
  maturity: string;
  /** platform → offers this field. */
  support: PlatformFlags;
  /** platform → caveat reason; presence means "offered with caveat" (✓△). */
  caveat?: PlatformCaveats;
}

export interface GuideTable {
  product: string;
  /** platform → offers this product at all (catalog). */
  offered: PlatformFlags;
  fields: GuideField[];
}

/** The four field-table keys, in the order they appear in `guide.json`. */
export type FieldTableName = 'Identity' | 'Engagement' | 'Audience' | 'Comments';

export interface GuideData {
  generatedAt: string;
  productsByPlatform: Partial<Record<Platform, string[]>>;
  tables: Record<FieldTableName, GuideTable>;
  audienceNote: string;
}

/** Products column set for the Products tab: [id, label]. */
export const PRODUCTS: ReadonlyArray<readonly [string, string]> = [
  ['identity', 'Identity'],
  ['audience', 'Audience'],
  ['engagement_new', 'Engagement'],
  ['engagement_deep', 'Engagement+'],
  ['stories', 'Stories'],
  ['mentions', 'Mentions'],
  ['comments', 'Comments'],
  ['ratings', 'Ratings'],
  ['ads', 'Ads'],
] as const;

/** Static token-lifecycle data — copied verbatim from the prototype. */
export interface TokenRow {
  platform: Platform;
  life: string;
  autoRefresh: boolean;
  note: string;
}

export const TOKENS: readonly TokenRow[] = [
  {
    platform: 'YouTube',
    life: '60 minutes',
    autoRefresh: true,
    note: 'OAuth refresh token. Invalidated by password change / permission revocation.',
  },
  {
    platform: 'Instagram',
    life: '60 days',
    autoRefresh: false,
    note: 'Long-lived token, re-extended before expiry by our refresh cron.',
  },
  {
    platform: 'TikTok',
    life: '24 hours',
    autoRefresh: true,
    note: 'Short-lived; refreshed continuously by cron.',
  },
  {
    platform: 'Threads',
    life: '60 days',
    autoRefresh: true,
    note: 'Long-lived; cron self-validates around day 53.',
  },
  {
    platform: 'Facebook',
    life: '60 days',
    autoRefresh: false,
    note: 'Long-lived page token.',
  },
  {
    platform: 'LinkedIn',
    life: '60 days',
    autoRefresh: true,
    note: 'Refresh token issued. Member + organization scopes.',
  },
  {
    platform: 'Twitch',
    life: '4 hours',
    autoRefresh: true,
    note: 'Short-lived; refreshed continuously by cron.',
  },
] as const;
